### ISSUE TITLE
Sistemazioni varie

### ISSUE THREAD

**Issue by lambrojos** [linkmesrl/elasticsearch-odm-5#1]
1- nome package json 
2- rendere questo https://github.com/linkmesrl/elasticsearch-odm-5/blob/es-5.x/index.js#L25 configurabile tramite variabile di ambiente ELASTICSEARCH_TRACE 
3- togliere le opzioni "ignore_conflicts" in https://github.com/linkmesrl/elasticsearch-odm-5/blob/es-5.x/index.js#L37
4- magari sistemare le branch dato che noi supporteremo solo elastic search 5.* e non ci serve la branch 2.*

**Comment by lollotek** [comment]
1- il nome era già modificato nel branch 5.x
2- aggiunto ELASTICSEARCH_TRACE e ELASTICSEARCH_LOGGING in develop
3- rimosso in develop
4- presenti le branch master e develop
